### ISSUE TITLE
[V10] Release Tracker

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#243]
> **Warning** The system will not be backwards compatible with V9.

## Blocking Issues
- [x] **Broken Roll Cards** #249
- [x] **Non Functional Journal Sheets** #250 
- [x] **Party travel page can disappear characters** #262 
- [x] **Editor's can't save text** #261
- [x] **V9 Created Journal Entries are corrupted** #265

**Comment by aMediocreDad** [comment]
**Broken Roll Cards** https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/issues/249

**Comment by aMediocreDad** [comment]
# First `Alpha` Release:
https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/tag/v10.0.0-0
