### ISSUE TITLE
Initiative tracker visuals are off

### ISSUE THREAD

**Issue by fougerec** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#267]
### Describe the bug

![image](https://user-images.githubusercontent.com/84296981/194300651-70792873-516b-4e67-a67f-4dd0e27b284e.png)
The Combat tracker doesn't seem to be working right.  This is V10, but Initiative is core system I believe which is flagged as being updated.

### Reproduction

Add actors to combat, open combat tracker

### System Info

```shell
Windows 10
Foundry V10.286
Forbidden Lands V10.0.0.4
No modules active
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).
