### ISSUE TITLE
5.0.0 Release

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#49]
Major Changes:
- [x] #47 - Weapon features that interact with attack actions.

Minor Changes:

- [x] #46 - Improved Chat Item links. Thanks to @moo-man
- [x] #44 - Monster types and Mount encumbrance calculation. Thanks to @roonel
- [x] #45 - Special Encumbrance values.
- [x] #36 - Alternative Actor/Item sheet interaction.

Localization:
- [x] #42 - Forbidden Lands now supports Spanish Language. Thanks to @DavidCMeier 
- [x] #50 - Forbidden Lands now supports Taiwanese Language. Thanks to @Rosataker 
- [x] #51 - Updated Czech localization. Thanks to @ptoseklukas

Fixes:
- [x] #41 Readme.md links fixed.
- [x] #48 Git localized badge added.
- [x] #39 Minor fixes to templates as partial references were affected by formatting.
- [x] #52 Hide exposed schemaVersion.
- [x] #53 Allow resizing of item sheets.

**Comment by giant-teapot** [comment]
+ #56 updated French localization.
